# 4. Submissions by track
# Datasource: https://data.linkeddatafragments.org/eswc2020
SELECT ?title ?track WHERE {
  ?submission a eswc2020:SubmissionsPaper;
    conference:title ?title;
    eswc2020:track [ rdfs:label ?track ].
}
